### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by Shentao83** [pfeilda/typo3samlauthentication#2]
The "External Manual" link is broken here. Could you please update the link? Is there another manual somewhere else?

https://extensions.typo3.org/extension/samlauthentication

**Comment by pfeilda** [comment]
yeah I will update the link this week with an update of the extension

**Comment by pfeilda** [comment]
@Shentao83 Link is fixed: https://pfeilda.github.io/typo3samlauthentication/
