### ISSUE TITLE
Howto configure type "SimpleSAMLphp SP"

### ISSUE THREAD

**Issue by cdaecke** [pfeilda/typo3samlauthentication#5]
First of all, thanks a lot for your nice extension!

At the moment I am trying to get the extension to work, by using the `SimpleSAMLphp SP`. Configuration in TYPO3 looks good to me, but how do I configure the service provider and identity provider in SimpleSAMLphp? I know, that I can add the configuration directly in the folder structure (in composer mode in `vendor/simplesamlphp/simplesamlphp/`), but this will be removed with the next update.

So what is the right way of configuring `SimpleSAMLphp` in your extension?

Thanks a lot for your help!

**Comment by pfeilda** [comment]
Hi, I'm not sure if i got your point.
Maybe we can schedule a call @cdaecke?

You have to configure SimpleSAMLphp SP or the Apache SP outside the extension (there is no other possibility).

**Comment by cdaecke** [comment]
Hi @pfeilda,

thanks for your offer! I would love to schedule a call with you. I have sent an email, with my contacts.

Cheers
chris
